import { POLLINATIONS } from "$env/static/private";

const configSQL = `Your only task is to convert the user's question into a single SQL query (PostgreSQL NEVER REPLY IN MARKDOWN AND ALWAYS PUT QUOTES IN COLUMNS AND TABLES NAMES. Use the database schema provided in the context. NEVER return text that is not pure SQL code. Use only the tables 'bovinos', 'FichaLactacao', 'OcorrenciaEvento', and 'AssociacaoBovinos' and use only its columns. If it is not possible to generate a query, return the string: null. When the user talks about "VacaXXXXXXX" or "TouroXXXXXXX" he's talking about the bovinos, nome column. table public."FichaLactacao" (dataencerramento date null, formacoleta text null, idademesesparto bigint null, "idAnimal" bigint null, ideventoparto bigint null, ideventoseca bigint null, numeroordenhas bigint null, qtdediaslactacao double precision null, qtdegordura305 double precision null, qtdeleite305 double precision null, qtdeproteinas305 double precision null, codigo character varying null, id bigint generated by default as identity not null); table public.bovinos (codigo character varying null default ''::character varying, "dataNascimento" timestamp without time zone null, nome character varying null, "paisOrigem" character varying null, raça bigint null, "idAnimal" bigint generated by default as identity not null, constraint bovinos_pkey primary key ("idAnimal")); create table public."OcorrenciaEvento" (id bigint generated by default as identity not null, "idAnimal" bigint not null, "dataOcorrencia" date null, facilidade_parto text null, nro_crias bigint null, qtde_litros bigint null, sexo_crias text null, tipo_evento bigint null, constraint OcorrenciaEvento_1_pkey primary key (id)); table public."AssociacaoBovinos" (ascendente_id bigint generated by default as identity not null, bovino_id bigint not null, situacao bigint null, tipo bigint null, id bigint generated by default as identity not null, constraint AssociacaoBovinos_pkey primary key (id)). tipo_evento (int): 7 means abertura_lactacao, 3 means cobertura, 2 means obito, 4 means 
ordenha, 1 means parto, 5 means pesagem, 6 means seca. \nWhenever a question is related to identifying the bull with the highest average milk production of daughters for a specific calving order, adapt this query to calculate the average for the requested order (first, second, third, etc.). Use the following SQL model as the base:\n\nWITH primeira_lactacao AS (\n    SELECT \n        f."idAnimal",\n        MIN(f.ideventoparto) AS primeiro_parto_evento\n    FROM public."FichaLactacao" f\n    WHERE f.qtdeleite305 IS NOT NULL\n    GROUP BY f."idAnimal"\n),\nlactacoes_primeiro_parto AS (\n    SELECT \n        f."idAnimal",\n        f.qtdeleite305\n    FROM public."FichaLactacao" f\n    INNER JOIN primeira_lactacao pl\n        ON f."idAnimal" = pl."idAnimal"\n        AND f.ideventoparto = pl.primeiro_parto_evento\n),\nfilhas_pais AS (\n    SELECT \n        ab.bovino_id AS id_filha,\n        ab.ascendente_id AS id_pai\n    FROM public."AssociacaoBovinos" ab\n),\nmedia_por_touro AS (\n    SELECT \n        t."nome" AS nome_touro,\n        AVG(lp.qtdeleite305) AS media_lactacao\n    FROM lactacoes_primeiro_parto lp\n    INNER JOIN filhas_pais fp ON lp."idAnimal" = fp.id_filha\n    INNER JOIN public.bovinos t ON t."idAnimal" = fp.id_pai\n    GROUP BY t."nome"\n)\nSELECT \n    nome_touro,\n    media_lactacao\nFROM media_por_touro\nORDER BY media_lactacao DESC\nLIMIT 1;\n`;
const configAnswer = `Your role is to transform the data resulting from an SQL query in JSON format into a coherent and user-friendly response. Use the original question and the data to generate the answer. If the data is empty, politely inform the user. If you run out in any problem, answer being honest and direct. DON'T TALK ABOUT TECHNICAL STUFF, LIKE SQL OR DATABASES. Don't offer help to fix problems or suggestions like that. tipo_evento (int): 7 means abertura_lactacao, 3 means cobertura, 2 means obito, 4 means ordenha, 1 means parto, 5 means pesagem, 6 means seca`;

// POLLINATIONS
export async function generateSQLQuery2(prompt) {
  const url = new URL(
    `https://text.pollinations.ai/${encodeURIComponent(prompt)}`
  );

  url.searchParams.set("model", "openai");
  url.searchParams.set("system", configSQL);
  url.searchParams.set("temperature", "1");

  const response = await fetch(url, {
    headers: {
      "Authorization": `Bearer ${POLLINATIONS}`, // substitua YOUR_API_KEY pelo token real
    },
  });

  const result = await response.text();
  return result;
}

// N8N
export async function generateSQLQuery(prompt) {
  const body = {
    prompt,
    system: configSQL,
  };

  const response = await fetch("https://lucas485.app.n8n.cloud/webhook/ai", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (response.status == 200) {
    return await response.text();
  } else {
    console.error(response.text());
    throw "Error generating SQL: " + response.text();
  }
}

// N8N
export async function generateFinalAnswer(prompt, data) {
  const body = {
    prompt: prompt + " SQL query result: " + JSON.stringify(data),
    system: configAnswer,
  };

  const response = await fetch("https://lucas485.app.n8n.cloud/webhook/ai", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (response.status == 200) {
    return await response.text();
  } else {
    console.error(response.text());
    throw "Error generating final answer: " + response.text();
  }
}

/*
export async function generateFinalAnswer(prompt, data) {
  const url = new URL(
    `https://text.pollinations.ai/${encodeURIComponent(
      prompt + " SQL query result: " + JSON.stringify(data)
    )}`
  );
  url.searchParams.set("model", "openai");
  url.searchParams.set("system", configAnswer);
  url.searchParams.set("temperature", "1");

  // console.log(url.href);
  const response = await fetch(url);
  const result = await response.text();
  return result;
}
*/
